# Linear Regression with TensorFlow

Table of contents:

- [Linear Regression Model](#linear-regression-model)
- [Gradient Descent](#gradient-descent)
- [Building a Model with TensorFlow](#building-a-model-with-tensorflow)

Linear regression is used to predict real-valued outputs. It is a parametric model and assumes a linear dependence/ relationship between the variables of the dataset.

<div style="display: inline-block;width: 100%;">
<img src="ieee-ompi/LinReg-1.png" style="float:left;" alt="Dataset with real-valued outputs." height=40% width=40% />
</div>

<a id="linear-regression-model"></a>

## Linear Regression Model
In a linear regression model, every variable (or feature vector) is assigned a specific weight (or parameter). We say that a weight parameterizes each feature in the dataset. The weights (or parameters) in the dataset are adjusted to find the optimal value (or constant) that scales the features to optimally approximate the values of the target (or output variable). The linear regression hypothesis is formally represented as:

$$h_{\theta}(x)=\theta_0+\theta_1 x_1+\theta_2 x_2+...+\theta_n x_n$$

To illustrate, the image below is a plot of the first feature and the target variable . We are plotting just one feature against the output variable because it is easier to visualize using a 2-D scatter plot.

<div style="display: inline-block;width: 100%;">
<img src="ieee-ompi/linear-scatter.png" style="float:left;" alt="Linear regression scatter plot." height=50% width=50% />
</div>

<span style="color:blue; font-weight:bold">The goal of the linear model:</span> is to find a line (or hyper-plane) that gives the best approximation or the best fit to the data points. In other words, we want to find a value for the weights $\theta_0$ and $\theta_1$ so that our hypothesis $h_{\theta}(x)$ is close to the target, $y$ for the example set. Hence the cost function can be defined as:

\begin{equation}
J(\theta) = \frac{1}{2m} \sum_{i=1}^{m} (h_\theta(x^{(i)}) - y^{(i)})^2
\end{equation}



When found, that line will look like the blue line in the image below.
<div style="display: inline-block;width: 100%;">
<img src="ieee-ompi/linear-scatter-regression.png" style="float:left;" alt="Scatter plot with the regression line." height=50% width=50% />
</div>

<a id="gradient-descent"></a>

## Gradient Descent
Gradient descent is an optimization algorithm that is used to minimize the cost function. Gradient descent attempts to find an approximate solution or the global minimum of the function space by moving iteratively in step along the path of steepest descent until a terminating condition is reached that stops the loop or the algorithm converges. It is expressed as:

\begin{equation}
\theta_j = \theta_j - \alpha \frac{\partial}{\partial \theta_j} J(\theta)
\end{equation}

where,
- $\theta$: is the parameter of the model
- $\alpha$: is the learning rate, which controls the step-size of the gradient update

An illusration of Gradient descent finding the global minimum of a convex function is shown below:
<div style="display: inline-block;width: 100%;">
<img src="ieee-ompi/contour-figure-gradient-descentb.png" style="float:left;" alt="Gradient Descent." height=50% width=50% />
</div>

## Building a Model with TensorFlow

In [7]:
# install TensorFlow 2.0
!pip install tf-nightly tensorflow

In [8]:
# import libraries
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

ImportError: Traceback (most recent call last):
  File "/Users/ekababisong/anaconda3/envs/pydl/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/ekababisong/anaconda3/envs/pydl/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/ekababisong/anaconda3/envs/pydl/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/ekababisong/anaconda3/envs/pydl/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/ekababisong/anaconda3/envs/pydl/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/ekababisong/anaconda3/envs/pydl/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: __ZN10tensorflow11NodeBuilderC1EN4absl11string_viewES2_PKNS_19OpRegistryInterfaceE
  Referenced from: /Users/ekababisong/anaconda3/envs/pydl/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Expected in: /Users/ekababisong/anaconda3/envs/pydl/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so
 in /Users/ekababisong/anaconda3/envs/pydl/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

In [4]:
# enable eager execution
tf.enable_eager_execution()

NameError: name 'tf' is not defined

<a id="importing-the-dataset"></a>

### Importing the dataset
The dataset used in this example is from the [Challenger USA Space Shuttle O-Ring Data Set* from the UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Challenger+USA+Space+Shuttle+O-Ring). The dataset contains 23 observations and 5 variables named:
- Number of O-rings at risk on a given flight 
- Number experiencing thermal distress 
- Launch temperature (degrees F)
- Leak-check pressure (psi)
- Temporal order of flight

The task is to predict the number of O-rings that will experience thermal distress for a given flight when the launch temperature is below freezing.

In [133]:
# import dataset
data = np.loadtxt("data/space-shuttle/o-ring-erosion-or-blowby.data")

In [134]:
# preview data
data[:10,:]

array([[  6.,   0.,  66.,  50.,   1.],
       [  6.,   1.,  70.,  50.,   2.],
       [  6.,   0.,  69.,  50.,   3.],
       [  6.,   0.,  68.,  50.,   4.],
       [  6.,   0.,  67.,  50.,   5.],
       [  6.,   0.,  72.,  50.,   6.],
       [  6.,   0.,  73., 100.,   7.],
       [  6.,   0.,  70., 100.,   8.],
       [  6.,   1.,  57., 200.,   9.],
       [  6.,   1.,  63., 200.,  10.]])

In [135]:
# number of rows and columns
data.shape

(23, 5)

<a id="prepare-the-dataset-for-modeling"></a>

### Prepare the dataset for modeling

In [136]:
# separate features and target
X = data[:,1:]
y = data[:,0]

In [137]:
# sample of features
X[:10,:]

array([[  0.,  66.,  50.,   1.],
       [  1.,  70.,  50.,   2.],
       [  0.,  69.,  50.,   3.],
       [  0.,  68.,  50.,   4.],
       [  0.,  67.,  50.,   5.],
       [  0.,  72.,  50.,   6.],
       [  0.,  73., 100.,   7.],
       [  0.,  70., 100.,   8.],
       [  1.,  57., 200.,   9.],
       [  1.,  63., 200.,  10.]])

In [138]:
# targets
y[:10]

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [139]:
# split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, test_size=0.15)

In [140]:
# standardize the dataset
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

In [141]:
# preview standardized feature matrix
X_train[:10,:]

array([[ 0.85895569, -1.75123631,  0.747545  , -0.44875031],
       [ 0.85895569,  0.1052245 , -1.49509   , -1.46033998],
       [ 0.85895569, -1.60843163,  0.747545  ,  1.57442904],
       [-0.62469505,  1.67607595,  0.747545  ,  0.85186499],
       [-0.62469505,  1.3904666 ,  0.747545  ,  1.14089061],
       [ 2.34260643, -2.32245502,  0.747545  ,  0.27381375],
       [-0.62469505,  0.81924789,  0.747545  ,  0.56283937],
       [-0.62469505,  0.53363853, -0.747545  , -0.73777593],
       [ 2.34260643,  0.81924789,  0.747545  ,  1.28540342],
       [-0.62469505, -0.46599421, -1.49509   , -1.60485279]])

<a></a>

### The Model

In [142]:
# parameters
m = len(X_train)   # length of training set
learning_rate = 0.01

In [143]:
# weight
W = np.random.randn(4).reshape(-1,1)
# bias term
b = np.random.randn()

In [144]:
# hypothesis
h_theta = tf.add(b, tf.matmul(X_train, W))

In [147]:
# cost function
cost = tf.reduce_mean(tf.square(h_theta - y_train))

In [148]:
# Gradient Descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate)

In [156]:
model = tf.keras.Sequential((
    tf.keras.layers.Dense(32, activation='relu', input_shape=X_train.shape),
    tf.keras.layers.Dense(1)))
model.build()
optimizer = tf.keras.optimizers.SGD()

In [157]:
def compute_loss():
    return tf.reduce_mean(tf.square(h_theta - y_train))

In [158]:
def compute_accuracy(labels):
    return tf.reduce_mean(tf.cast(tf.equal(predictions, labels), tf.float32))

In [159]:
def train_one_step(model, optimizer, x, y):
    with tf.GradientTape() as tape:
        tape.watch(model.trainable_variables)
        logits = model(x)
        loss = compute_loss(logits, y)

    grads = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))
    
    accuracy = compute_accuracy(logits, y)
    return loss, accuracy

In [160]:
@tf.function
def train(model, optimizer):
    train_ds = mnist_dataset()
    step = 0
    loss = 0.0
    accuracy = 0.0
    for x, y in train_ds:
        step += 1
        loss, accuracy = train_one_step(model, optimizer, x, y)
        if tf.equal(step % 10, 0):
            tf.print('Step', step, ': loss', loss, '; accuracy', accuracy)
    return step, loss, accuracy

AttributeError: module 'tensorflow' has no attribute 'function'